name: Terraform with Localstack Test

on:
    push:
        branches-ignore:
            - "main"

jobs:

    terraform-validate:
        runs-on: ubuntu-latest
        
        steps:
        
          - name: checkout branch
            uses: actions/checkout@v2
            
          - name: Run terraform validate
            run: |
                terraform -chdir=tests init
                terraform -chdir=tests validade
        
    terraform-apply:
        runs-on: ubuntu-latest
        needs: terraform-validate
        steps:
            - name: checkout branch
              uses: actions/checkout@v2
            
            - name: asdf_install
              uses: asdf-vm/actions/install@v1
            
            - name: Start Localstack
              run: |
                python3 -m pip install localstack awscli-local pyOpenSSL cryptography
                docker pull localstack/localstack
                localstack sttart -d 
                echo "Waiting for localstack startup"
                localstack eait -t 60
                docker ps -a
                echo "Startup Complete"
            
            - name: Run Terraform Plan
              run: |
                terraform -chdir=tests init
                terraform -chdir=tests plan
            
            - name: Run Terraform Apply
              run: | 
                terraform -chdir=tests init
                terraform -chdir=tests apply -auto-approve